tonApp/urls.py
from django.urls import path
from tonApp.views import *
app_name='tonApp'
urlpatterns = [
    path('',homePage,name="tonApp-homePage"),
    path("aboutUs",aboutUs,name="aboutUs"),
    path("service",Service,name="service"),
    path("join",joinUs,name="joinUs"),
    path('coachingservice',Coaching,name="coaching"),
    path('mentoringService',Mentoring,name="mentoring"),
    path('discoveringService',Discovering,name="Discovering"),
    path('coordonneeForm',UserCoordonnees,name="CoordonneeUser"),#formulaire des coordonnees des utilisateur
    path('TalentService',Talent,name="talent"),
    path('pointOfView',PointOfView,name="POV"),
    path('improvement',Improvement,name="improvement"),
    path('OpenlessWoldWild',WorldWild,name="worldWild"),
    path('Legacy',legacy,name="legacy"),
    path('logo',Logo,name="logo"),
]

tonAppManagement/urls.py
from django.urls import path
from tonAppManagement.views import *


app_name='tonAppManagement'
urlpatterns=[
    path('mailPage',Mail,name="mail"),
    path('Comment/<str:commentaireId>',Comment,name="comment"),
    path('AboutUser',Coordonnee,name="userInfo"),
    path('home',index,name="homePage"),
    #path('filter/<int:infoId>',Filtre,name="filtre"),
]

twentyOneNetwork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tonAppManagement.urls')),
    
]

urlpatterns += i18n_patterns(
    path((''),include('tonApp.urls'),name="langue"),
)

tonApp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
#irheritierhtb/htb115

class Commentaire(models.Model):
    Nom=models.CharField(max_length=20,verbose_name=_("Name"))
    Mail=models.EmailField(primary_key=True,verbose_name=_("Mail"))
    message=models.TextField(max_length=1000,verbose_name=_("Message"))
    Tel=models.CharField(max_length=13,unique=True,verbose_name=_("Phone"))
    def __str__(self):
        return f"{self.Nom}"


# Create your models here.

tonAppManagement/models.py
from django.db import models

class Services(models.Model):
    """Services table """
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class UserInformations(models.Model):
    """table of users informations """
    firstname=models.CharField(max_length=50)
    secondname=models.CharField(max_length=40)
    service=models.CharField(max_length=50)
    number=models.IntegerField()
    email=models.EmailField()
    etat=[("T","traité"),
          ("N","Non traité")
    ]
    status=models.CharField(max_length=20,choices=etat)
    def __str__(self) -> str:
        return self.firstname

tonApp/forms.py
from django import forms
from tonApp.models import Commentaire
class UserMessage(forms.ModelForm):
    class Meta:
        model=Commentaire
        fields=['Nom','Mail','Tel','message',]
    

tonAppManagement/forms.py
from django import forms
from django.forms import ModelForm
from tonAppManagement.models import UserInformations


class UserForm(ModelForm):
    """User form"""
    class Meta:
        model=UserInformations
        fields=['firstname','secondname','service','number','email',]

tonApp/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from tonApp.forms import UserMessage
from tonAppManagement.models import Services
from tonAppManagement.forms import UserForm
from tonApp.models import *
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext as _,ngettext
# Create your views here.
    
def homePage(request):
    """la definition de la vue de la page principale"""
    text=_("Knowledge is the key for a best futur. wherever you are, Network twenty one is there to accompany you with its services.")
    if request.method=='POST':
        form=UserMessage(request.POST)
        if form.is_valid():

            form.save()
            return redirect('tonApp-homePage')
    else:
        form=UserMessage()
    return render(request,"Network 21 Formation.html",context={"date": datetime.today(),'Formulaire':form,'text':text})
def aboutUs(request):
    """View of abous us """
    return render(request,"aboutUs.html")

def Logo(request):
    """View logo"""
    return render(request,'logoPage.html',{})
def Service(request):
    return render(request,"Service.html")
def joinUs(request):
    return render(request,"joinUs.html")

def Coaching(request):
    return render(request,'Services/coaching.html',context={"Date": datetime.today()})

def Mentoring(request):
    return render(request,'Services/mentoring.html',context={"Date": datetime.today()})

def Discovering(request):
    return render(request,'Services/Discovering.html',context={"Date": datetime.today()})

def Talent(request):
    return render(request,'Services/Talent.html',context={})

def PointOfView(request):
    return render(request,'Services/pointOfview.html',context={})

def Improvement(request):
    return render(request,'Services/improvement.html',context={})

def WorldWild(request):
    return render(request,'Services/openWorldWild.html',context={})

def legacy(request):
    return render(request,'Services/legacy.html',context={'Houre':datetime.now(),'Id':1})

def UserCoordonnees(request):
    #Form of user
    services=Services.objects.all()
    if request.method=="POST":
        form=UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tonApp:CoordonneeUser')
        else:
            form=UserForm()
    return render(request,'Services/coordonnee.html',{'services':services}) 
# Create your views here.

tonAppManagement/views.py
from django.shortcuts import render,redirect
from tonAppManagement.models import UserInformations
from tonApp.models import Commentaire
from datetime import datetime

def index(request):
    return render(request,'UserManagement/index.html')

def Mail(request):
    Commentaires=Commentaire.objects.all()
    return render(request,'UserManagement/mailPage.html',{'commentaires':Commentaires})

def Comment(request,commentaireId):
    Comments=Commentaire.objects.filter(pk=commentaireId)
    return render(request,'UserManagement/commentaire.html',{'comments':Comments})

def Coordonnee(request):
    """View of user information"""
    userInfo=UserInformations.objects.all()
    if request.method=="GET":
        search=request.GET.get('chercher')
        if search is not None:
            userInfo=UserInformations.objects.filter(firstname__iexact=search)
        else:
            userInfo=UserInformations.objects.all()
    return render(request,'UserManagement/CordonneesUser.html',context={'userInfos':userInfo,'date':datetime.now()})

"""def Filtre(request,infoId):
    userInfo=UserInformations.objects.get(pk=infoId)
    return render(request,'UserManagement/CordonneesUser.html',context={'userInfos':userInfo,'date':datetime.now()})
"""

tonApp/templates/Network 21 Formation.html
{% load static %}
{% load i18n%}
{% get_available_languages as LANGUAGES%}
{% get_language_info_list for LANGUAGES as Languages%}
<!doctype html>
<html>
<head>
<title>Twenty-one network</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'css/homeStyle.css' %}" />
<link rel="stylesheet" href="{% static 'css/mobileStyle.css'%} " media="only screen and (max-width: 425px)">
</head>
<body>
    <header>
         
            <div class="nav_toggle">
                <span class="line l1"></span>
                <span class="line l2"></span>
                <span class="line l3"></span>
            </div>
            <div class="letters">
                
                <div class="letter">N</div>
                <div class="letter">e</div>
                <div class="letter">t</div>
                <div class="letter">w</div>
                <div class="letter">o</div>
                <div class="letter">r</div>
                <div class="letter">k</div>
                
                <div class="letter"> T</div>
                <div class="letter">w</div>
                <div class="letter">e</div>
                <div class="letter">n</div>
                <div class="letter">t</div>
                <div class="letter">y</div>
                <div class="letter">-</div>
                <div class="letter">O</div>
                <div class="letter">n</div>
                <div class="letter">e</div>
            
                <div class="letter">K</div>
                <div class="letter">B</div>
                <div class="letter">L</div>
                <div class="letter">D</div>
                <div class="letter">R</div>
                <div class="letter">C</div>
            </div>
       <div class="blockNav">
            <div class="dropdown-toggle"><p>Language</p>
              
                <ul class="sous-menu">
                    {% for language  in Languages %}
                <li><a href="/{{language.code}}">{{language.name_local}}</a></li>
                {% endfor %}
              
                </ul>
            </div>
        <ul class="nav-description">
            <li><a href="{% url 'tonApp:tonApp-homePage' %}">{% trans "Home"%}</a></li>
            <li><a href="{% url 'tonApp:aboutUs' %}">{% trans "About us"%}</a></li>
            <li><a href="" class="Contact">{% trans "Contact us" %}</a></li>
            <li><a href="{% url 'tonApp:joinUs' %}">{% trans "Join-us" %}</a></li>
            <li><a href="{% url 'tonApp:service'%}">{% trans "Services" %}</a></li>
        </ul>
    </div>
    </header>
    <section style="background-image: url('{% static 'Pictures/fille souriante.jpg'%}');background-position: center; z-index: 500;">
        <div class="text">
            <p class="Presentation"> {% trans "You're welcome on network twenty-one site<br>  Knowledge is the key for a best futur<br> wherever you are, <b>Network twenty one</b> is there to accompany you with its services." %}
            <br> {{date}} </p>
            
            <img src="{% static 'Pictures/logo_network21.PNG' %}" class="logo" alt="image non-retrouve"
            height="150" width="150" >
            
            
        </div>

    </section>
    <div class="serviceContain">
      
       
       <div class="Coaching">
        <img src="{% static 'Pictures/coache in coaching.jpg' %}" alt="non retrouvé" height="50%" width="100%">
        {% trans "<p><b>Coaching</b><br>the best way to predict the future is to create it. in this way you need to improve your capacities and motivation. and we're there to lead you to success of your bussiness... </p>" %}
            <a href="{% url 'tonApp:coaching' %}" class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>
        </div>
       <div class="mentoring">
        <img src="{%static 'Pictures/mentor in mentoring.JPEG' %}" alt="non retrouvé" height="50%" width="100%">
        {% trans "<p><b>Mentoring</b></br>For going somewhere better to be accompanied by someone who has already gone at the place twenty-one network offer you a good service of mantoring with the bests mentor...</p>"%}
             <a href="{% url 'tonApp:mentoring'%}" class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>
        </div>
       <div class="discovering">
       <img src="{%static 'Pictures/istockphoto-675974978-170667a.jpg' %}" alt="non retrouvé" height="50%" width="100%">
       {% trans "<p><b>discovering your self</b><br><span>A man is created with capacity to <b>be</b> and <b>do</b>, network twenty-one help you to know and exploit the capacity containing in you ...</span> "%}
        <a href="{% url 'tonApp:Discovering' %}" class="Link-ReadMore" style="margin-left: 14em; position:relative; top:3em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>      
      </div>
      
        <div class="pointOfVew">
            <img src="{%static 'Pictures/pexels-fauxels-3184360.jpg'%}" alt="non retrouvé" height="50%" width="100%">
            {% trans " <p><b>Point of view</b></br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis, quae rerum. Totam minus, tenetur neque dicta non quibusdam distinctio odit vel minima reiciendis eligendi hic voluptatibus eveniet dolor quis consectetur?</p> "%}
                <a href="{% url 'tonApp:POV'%}" class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:0.1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>    
                </div>
        
         <div class="legacy">
            <img src="{%static 'Pictures/pexels-photo-8190804.jpeg' %}" alt="non retrouvé" height="50%" width="100%">
            {% trans " <p><b>legacy</b><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis, quae rerum. Totam minus, tenetur neque dicta non quibusdam distinctio odit vel minima reiciendis eligendi hic voluptatibus eveniet dolor quis consectetur?"%}</p>
            <a href="{% url 'tonApp:legacy' %}" class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:0.1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a> 
               </div>
        <div class="openlessWoldWild">
            <img src="{%static 'Pictures/1689519938107.jpeg' %}" alt="non retrouvé" height="50%" width="100%">
            {% trans "<p><b>openlessWoldWild</b><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis, quae rerum. Totam minus, tenetur neque dicta non quibusdam distinctio odit vel minima reiciendis eligendi hic voluptatibus eveniet dolor quis consectetur?"%}</p>
            <a href="{% url 'tonApp:worldWild'%}" class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:0.1em;height:2vh;  color:rgb(204, 202, 202); background-color: green;padding: 5px; text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>
        </div>
            <div class="Talent">
                <img src="{%static 'Pictures/pexels-photo-3880782.jpeg' %}" alt="non retrouvé" height="50%" width="100%">
                {% trans "Talent<p><b>Talent</b><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis, quae rerum. Totam minus, tenetur neque dicta non quibusdam distinctio odit vel minima reiciendis eligendi hic voluptatibus eveniet dolor quis consectetur?"%}</p>
               <a href="{% url 'tonApp:talent'%}"class="Link-ReadMore" style="margin-left: 14.3em; position:relative; top:0.1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..."%}</a>          
                  </div>
                
                  <div class="emprovement">
                    <img src="{%static 'Pictures/photo-manager-plan-to-improve-quality.jpg' %}" alt="non retrouvé" height="50%" width="100%">
                    {% trans "Talent<p><b>Improvement</b></br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis, quae rerum. Totam minus, tenetur neque dicta non quibusdam distinctio odit vel minima reiciendis eligendi hic voluptatibus eveniet dolor quis consectetur?"%}</p>
                        <a href="{% url 'tonApp:improvement'%}" class="Link-ReadMore"  style="margin-left: 14.3em; position:relative; top:0.1em;height:2vh; color:rgb(204, 202, 202); background-color: green;padding: 5px;text-decoration: none;" title="lire plus">{% trans "Read more..." %}</a>           
                         </div>
    </div>
   
    <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
    <script>
        let text= new Typed(".Contenu",{
            strings:["You're welcome on network twenty-one site"],
            typeSpeed:150,
            backSpeed:150,
            loop:true
        })
    </script>
    <script nomodule><p>Activate your javascript in your navigator please </p> </script>
</body>
<footer> 
    <div class="join">
        <p><h2>{% trans "Join us on :"%}</h2></p>
       <p><img src="{% static 'Pictures/facebookLogo.png'%}" alt="image non-retrouve" width="50" height="50" style="border-radius: 50%;"><a href="#"><a href="#">Facebook</a></p>
        <p><img src="{%static 'Pictures/instagram.jpeg'%}" alt="image non-retrouve" width="50px" height="50" style="border-radius: 50%;"><a href="#"></a>Instagram</a></p>
        <p><img src="{%static 'Pictures/tik-tok-logo.png'%}" alt="image non-retrouve" width="50px"><a href="#"></a>Tiktop</a></p>
        <p><img src="{%static 'Pictures/twitter-logo.png'%}" alt="image non-retrouve" width="50px"><a href="#"></a>Twiter</a></p>
<img src="{% static 'Pictures/linkdin logo.jpeg' %}" alt="image non-retrouve" width="50px" style="border-radius: 50%;"><a href="#"></a>linkdIn</a></p>
    </div>
    <div class="Email">
        <form method="post">
            {% csrf_token %}
        <p><h2>{% trans "For more information let's a message"%} </h2></p>
        {{Formulaire.as_p}}
       <input type="submit"  class="Validation" value="Submit">
    </form>
</div>
<div class="callContacts">
    <h2>{% trans "Here's our contacts"%}</h2>
    <p><img src="{%static 'Pictures/whatsapp.png' %}" alt="image non retrouvé" width="25">: +243 85 416 60 45</p>
    <p><img src="{%static 'Pictures/call logo.jpeg' %}" alt="image non retrouvé" width="25" style="border-radius: 50%;">: +243 99 116 20 45</p>
    <span class="Contenu"></span>
</div>
</footer>
</html>

tonApp/templates/Services/Coordonnee.html
{%load static%}
{% load i18n%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form of user informations </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/FormStyle.css' %}" />
</head>
<body>
    <div class="container">
    <div class="twentyOneNetworkLogo">
        <img src="{% static 'Pictures/Logo network twenty one.JPG' %}" alt="not found" width="50%">
        {%" trans "<p>Hello !</p> " %}
    </div>
<div class="formulaire">
    <img src="{% static 'Pictures/images (3).png' %}" width="50" style="border-radius: 50%;" alt="image not found"><p><h2>Get in touch</h2></p>
    <form action="" method="post">
        {% csrf_token %}
        <p><input type="text" placeholder="Enter your first name " name="firstname" required></p>
        <p><input type="text" placeholder="Enter your second name " name="secondname" required></p>
        <p><select name="service" id="serviceOption" >
            {% for service in services%}
            <option >{{service.name}}</option>
            {%endfor%}
        </select></p>
        <p><input type="tel" placeholder="Enter your phone number" name="number" required></p>
       <p> <input type="email" placeholder="Enter your email" name="email" ></p>
        <p><input type="submit" value="Send"></p>
    </form>
   
</div>
</div>
</body>
</html>

tonApp/templates/Services/coaching.html
{%load static %}
{% load i18n%}
<!doctype html>
<html>
<head>
<title>{%block title%}Coaching service{% endblock%}</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'css/homeStyle.css' %}" />
</head>
<body>
        {%block Content %}
   <div class="headerCoaching">

   </div>
   
   <div class="contentCoaching">
        <div class="sectionCoaching" style="background-image: url('{%static 'Pictures/coache in coaching.jpg' %}'); background-size: cover;">
                 
               {% trans " <p>Welcom in Coaching service<br> below you will found all details about coaching.<br> "%}

                    {{Date}}</p>
               </div>
        <div class="contentCoachingText">
                {% blocktranslate %}
       <p><b>Coaching</b> is about personal development and growth. Our one-on-one coaching sessions cater 
        to various aspects of life, from career and confidence building to stress management and
        creativity. Let our experienced coaches guide you toward your goals.</p>
        <p><b>In this service we're offering these kind of coaching service below</b></p>
         <span><b>Development Coaching:</b> Offer one-on-one coaching sessions to help individuals 
         and achieve personal and professional goals.</span></br> 
         <span><b>Career Coaching:</b> Provide guidance and support for career advancement, job search 
strategies, and professional development.</span><br>
         <span><b>Life Balance Coaching:</b> Assist individuals in finding a healthy balance between work, 
personal life, and well-being.</span><br>
        <span><b>Confidence and Self-Esteem Coaching:</b> Help individuals boost their confidence, develop a 
positive self-image, and overcome self-doubt.</span><br>
        <span><b>Relationship Coaching:</b> Offer insights and strategies for building and maintaining healthy 
relationships, whether romantic, familial, or professional.</span>
                {% endblocktranslate%}
        </div> 
   
       
        <div class="contenCoachingText1">
                {% blocktranslate %}
          <span><b>Leadership Coaching:</b> Provide coaching for individuals looking to enhance their leadership 
skills and effectively manage teams. </span><br>
            <span><b>Stress Management Coaching:</b> Assist individuals in managing stress, developing coping 
strategies, and improving overall resilience. </span><br>
            <span><b>Communication Skills Coaching:</b> Offer guidance on improving interpersonal 
communication, public speaking, and effective dialogue. </span><br>
            <span><b>Health and Wellness Coaching:</b> Provide support for adopting healthy habits, improving 
fitness, and achieving overall wellness goals. </span><br>
            <span><b>Time Management Coaching:</b> Help individuals optimize their time, prioritize tasks, and 
achieve better work-life balance.</span><br>
            <span><b>Creativity Coaching:</b> Assist individuals in overcoming creative blocks, fostering 
innovation, and tapping into their creative potential.</span><br>
            <span><b> Setting and Achievement Coaching: </b> individuals in setting actionable goals, 
developing plans, and tracking progress.</span>
        </div>
        {% endblocktranslate %}
        <div class="Button">
       <a href="{%url 'tonApp:CoordonneeUser' %}"> <p  style="background-color:rgb(212, 223, 226);color: red; 
       font-size: 2rem; font-family: century 'sens-serif'; width: 10vw;height: 5vh;
       margin-left: 35vw; text-align: center;padding: 10px; border-radius: 50px;
        ">{% trans " Start "%}</p></a>
        </div>
    </div>
  {%endblock%}
   <footer>
        <div class="join">
                <p><h2>{% trans " Join us on : "%}</h2></p>
                <a href="#"><a href="#"><p><img src="{% static 'Pictures/facebookLogo.png'%}" alt="image non-retrouve" width="50" height="50" style="border-radius: 50%;">Facebook</p></a>
                <a href="#"><p><img src="{%static 'Pictures/instagram.jpeg'%}" alt="image non-retrouve" width="50px" height="50" style="border-radius: 50%;">Instagram</p></a>
                <a href="#"><p><img src="{%static 'Pictures/tik-tok-logo.png'%}" alt="image non-retrouve" width="50px">Tiktop</p></a>
                <a href="#"><p><img src="{%static 'Pictures/twitter-logo.png'%}" alt="image non-retrouve" width="50px">Twiter</p></a>
                <a href="#"><img src="{% static 'Pictures/linkdin logo.jpeg' %}" alt="image non-retrouve" width="50px" style="border-radius: 50%;">linkdIn</p></a>
            </div>
            <div class="aboutTonLink">
                <li><a href="{% url 'tonApp:tonApp-homePage' %}">Home</a></li>
                <li><a href="{% url 'tonApp:aboutUs' %}">About us</a></li>
            </div>
        <div class="callContacts">
            <p><img src="{%static 'Pictures/whatsapp.png' %}" alt="image non retrouvé" width="25">: +243 85 416 60 45</p>
            <p><img src="{%static 'Pictures/call logo.jpeg' %}" alt="image non retrouvé" width="25" style="border-radius: 50%;">: +243 99 116 20 45</p>
        </div>
   </footer>
</body>
</html>

tonApp/templates/aboutUs.html
{%load static%}
{% load i18n%}
<!doctype html>
<html>
<head>
<title> Anout us</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'css/homeStyle.css' %}" />
</head>
<body>

    <div class="AboutUs" style="background-size:fix; background-image: url('{% static 'Pictures/fille_souriante_sappuillant_sur.JPEG' %}');
        background-position: 5rem; object-fit:cover; ">

               <a href="{% url 'tonApp:logo' %}" ><img src="{% static 'Pictures/logo_network21.PNG' %}" height="200px" width="200px" /></a>
                  {% blocktranslate %}
                  <p> We are world's champions uplifting human ressources.
                    <br> Mision : our vision is to keep researches alive for future generations as a part of legacy.<br>
                    Vision: bringing educationnal world system's available for old schools accessible toward the seminar's conferences and workshops, professional training.
                </p>
                {% endblocktranslate %}
<!-- au niveau de la presentation on doit enlever we're worlds ... par le la presentation de l'entreprise  -->
<div class="aboutUsInfo">
    <span><a href="{% url 'tonApp:tonApp-homePage' %}" >{% trans "Home " %}</a></span>
    <span><a href="#" class="member">{% trans "Become member"%}</a></span>
</div>
</div>
</body>
</html>

tonApp/templates/contactUs.html
<!doctype html>
<html>
<head>
<title> Contact us</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'css/'%}" />
</head>
<body style="background-color: rgb(72,145,145);margin-top: 25%;margin-left: 25%;">
<p style="color :rgb(72,145,145)"><h1>Cette page n'est pas encore disponible</p></h1>
</body>
</html>

tonApp/templates/joinUs.html
<!doctype html>
<html>
<head>
<title> join us</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="homeStyle.css" />
</head>
<body style="background-color: rgb(72,145,145);margin-top: 25%;margin-left: 25%;">
    <p style="color :rgb(72,145,145)"><h1>Cette page n'est pas encore disponible</p></h1>
</body>
</html>

tonApp/templates/logoPage.html
{% load static %}
<!doctype html>
<html>
<head>
<title> Anout us</title>
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="" />
</head>
<body>


                <img src="{% static 'Pictures/logo_network21.PNG' %}" height="50%" width="35%" style="position: absolute;top:30%;left:30%;"/>
                
</body>
</html>

tonAppManagement/templates/UserManagement/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}index{%endblock%}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/tonStyle.css' %}" />
</head>
<body>
 
   <nav>
    <div class="navHeadTitle">
        <img src="{% static 'Pictures/Logo network twenty one.JPG' %}" alt="Not found" height=70px" width="70px" style="border-radius: 60%;">
    <span>Twenty-one network</span>
</div>
    <a href="#">Tableau de bord</a>
    <a href="#">Services</a>
    <a href="{% url 'tonAppManagement:userInfo' %}">Coordonnees utilisateur</a>
    <a href="#">Encadreur</a>
    <a href="#">Invité</a>
    <a href="#">Participant</a>
    <a href="#">Conference</a>
    <a href="{% url 'tonAppManagement:mail' %}">Messages</a>
    <a href="">Parametre</a>
    </nav>
    <div class="ronds">
        <div class="ron R1"></div>
        <div class="ron R2"></div>
        <div class="ron R3"></div>
        <div class="ron R4"></div>
        <div class="ron R5"></div>
       </div>
    {% block Content %}
    <!-- les elements des templates fils sont inseres ici -->
   {%endblock%}
</body>
</html>